from tkinter import *
from tkinter import Tk, StringVar

#region GUI
root = Tk()
root.title("Frog's Secret Oven")
root.configure(background='black')
root.geometry("700x700+0+0")
root.resizable(width=False, height=False)
TitleFrame = Frame (root, width = 600, height = 100, bd = 12, relief = "raise",bg="lightgreen")
TitleFrame.pack(side=TOP)
lblTitle = Label(TitleFrame, background ='green', text="\t\tFrog's Secret Oven\t\t")
lblTitle.grid(row=0, column=0)
MainBody = Frame (root,background='#000000', width = 600, height = 500, bd = 12, relief = "raise")
MainBody.pack(side=BOTTOM, fill="both", expand=True)
LeftFrame = Frame (MainBody, background='green', width =300 ,height = 500, bd=12, relief = "raise")
LeftFrame.pack(side=LEFT,fill="both",expand=True)
RightFrame = Frame (MainBody,  background='green', width = 300, height = 500, bd = 12, relief = "raise")
RightFrame.pack(side=LEFT)
RightFrameTop = Frame (RightFrame,  background='green', width = 300, height = 400, bd = 4, relief = "raise")
RightFrameTop.pack(side=TOP)
RightFrameBottom = Frame (RightFrame, width = 300, height = 200, background='green', bd = 4, relief = "raise")
RightFrameBottom.pack(side=BOTTOM)
#endregion
#region Variables
var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11= IntVar()
var12= IntVar()
var13 = IntVar()
var14 = IntVar()
var15= IntVar()
var16 = IntVar()
var17= IntVar()
var18= IntVar() 
var19= IntVar()
var20= IntVar()
var21= IntVar()
var22= IntVar()
var23= IntVar()
var24= IntVar()
var25= IntVar()
var26= IntVar()
var27= IntVar()
var28= IntVar()
var29= IntVar()
var30= IntVar()
var31= IntVar()
var32 = IntVar()
var33 = StringVar()
KetchupValue = StringVar()
KetchupValue.set("0")
MayoValue = StringVar()
MayoValue.set("0")
BarbecueValue= StringVar()
BarbecueValue.set("0")
MustardValue= StringVar()
MustardValue.set("0")
SalsaValue= StringVar()
SalsaValue.set("0")
OliveValue= StringVar()
OliveValue.set("0")
PumpkinValue= StringVar()
PumpkinValue.set("0")
ArabicSpicyValue=StringVar()
ArabicSpicyValue.set("0")
ArabicMildValue=StringVar()
ArabicMildValue.set("0")
DanishValue=StringVar()
DanishValue.set("0")
HorseradishValue=StringVar()
HorseradishValue.set("0")
TeaValueuffing=StringVar()
TeaValueuffing.set("0")
StudentValue=StringVar()
StudentValue.set("0")
WeganValue=StringVar()
WeganValue.set("0")
FishermanValue=StringVar()
FishermanValue.set("0")
MarioValue=StringVar()
MarioValue.set("0")
SchrödingeraValue=StringVar()
SchrödingeraValue.set("0")
RiemannValue=StringVar()
RiemannValue.set("0")
TarzanValue=StringVar()
TarzanValue.set("0")
HunterValue=StringVar()
HunterValue.set("0")
CheeseValue=StringVar()
CheeseValue.set("0")
FrogsSecretSauceValue=StringVar()
FrogsSecretSauceValue.set("0")
LuigiValue=StringVar()
LuigiValue.set("0")
OrissaValue=StringVar()
OrissaValue.set("0")
MasterpieceValue=StringVar()
MasterpieceValue.set("0")
varVeganMac=StringVar()
varVeganMac.set("0")
varSweetPotatoFritters=StringVar()
varSweetPotatoFritters.set("0")
VillageValue=StringVar()
VillageValue.set("0")
varChange=StringVar()
varChange.set("0")
FinalValue=StringVar()
FinalValue.set("0")
TotalValue=StringVar()
TotalValue.set("0")
TipValue=StringVar()
TipValue.set("0")
varPayment=IntVar()
varPayment.set("0")
varVAT=StringVar()
varVAT.set("")
WaterValue=StringVar()
WaterValue.set("0")
PepsiValue=StringVar()
PepsiValue.set("0")
CoffeeValue=StringVar()
CoffeeValue.set("0")
TeaValue=StringVar()
TeaValue.set("0")
FrogMixtureValue=StringVar()
FrogMixtureValue.set("0")
#endregion
#region FUNCTIONS
def ExitButton(root) :
	root.destroy()
	return
def Reset():
    var1.set(0)
    var2.set(0)
    var3.set(0)
    var4.set(0)
    var5.set(0)
    var6.set(0)
    var7.set(0)
    var8.set(0)
    var9.set(0)
    var10.set(0)
    var11.set(0)
    var12.set(0)
    var13.set(0)
    var14.set(0)
    var15.set(0)
    var16.set(0)
    var17.set(0)
    var18.set(0)
    var19.set(0)
    var20.set(0)
    var21.set(0)
    var22.set(0)
    var23.set(0)
    var24.set(0)
    var25.set(0)
    var26.set(0)
    var27.set(0)
    var28.set(0)
    var29.set(0)
    var30.set(0)
    var31.set(0)
    var32.set(0)
    KetchupValue.set("0")
    MayoValue.set("0")
    BarbecueValue.set("0")
    MustardValue.set("0")
    SalsaValue.set("0")
    OliveValue.set("0")
    PumpkinValue.set("0")
    ArabicSpicyValue.set("0")
    ArabicMildValue.set("0")
    DanishValue.set("0")
    HorseradishValue.set("0")
    TeaValueuffing.set("0")
    StudentValue.set("0")
    WeganValue.set("0")
    FishermanValue.set("0")
    MarioValue.set("0")
    SchrödingeraValue.set("0")
    RiemannValue.set("0")
    TarzanValue.set("0")
    HunterValue.set("0")
    CheeseValue.set("0")
    FrogsSecretSauceValue.set("0")
    LuigiValue.set("0")
    OrissaValue.set("0")
    MasterpieceValue.set("0")
    varVeganMac.set("0")
    varSweetPotatoFritters.set("0")
    VillageValue.set("0")
    varChange.set(" ")
    FinalValue.set("0")
    TipValue.set("0")
    TotalValue.set("0")
    varVAT.set("")
    varPayment.set(" ")
    WaterValue.set("0")
    PepsiValue.set("0")
    CoffeeValue.set("0")
    TeaValue.set("0")
    FrogMixtureValue.set("0")
def FinalCountdown():
    Ketc = float(KetchupValue.get())
    Mayo = float(MayoValue.get())
    Barb = float(BarbecueValue.get())
    Must = float(MustardValue.get())
    Sals = float(SalsaValue.get())
    Oliv = float(OliveValue.get())
    Pump = float(PumpkinValue.get())
    AraS = float(ArabicSpicyValue.get())
    AraM = float(ArabicMildValue.get())
    Dani = float(DanishValue.get())
    Hors = float(HorseradishValue.get())
    Hunt = float(HunterValue.get())
    Chee = float(CheeseValue.get())
    Frog = float(FrogsSecretSauceValue.get())
    Mari = float(MarioValue.get())
    Schr = float(SchrödingeraValue.get())
    Riem = float(RiemannValue.get())
    Tarz = float(TarzanValue.get())
    Stud = float(StudentValue.get())
    Wega = float(WeganValue.get())
    Fish = float(FishermanValue.get())
    Luig = float(LuigiValue.get())
    Oris= float(OrissaValue.get())
    Master = float(MasterpieceValue.get())
    Vill= float(VillageValue.get())
    Wate= float(WaterValue.get())
    Peps = float(PepsiValue.get())
    Coff = float(CoffeeValue.get())
    Tea = float(TeaValue.get())
    FroM = float(FrogMixtureValue.get())
    SaucesCost = ( (Ketc * 2.00) + (Mayo * 2.00) + (Barb * 2.50) + (Must * 2.50) + (Sals * 3.00 ) + (Oliv * 2.50) +(Pump * 3.50) + (AraS * 3.50) + (AraM * 2.50) + (Dani * 3.50) + (Hors * 2.50 ) + (Hunt * 2.50) +(Chee * 3.50) + (Frog * 6.50))
    DrinksCost = ((Wate * 0.50) + (Peps * 1.50) + (Coff * 1.25) + (Tea * 1.50 ) + (FroM * 6.50))
    PizzaCost = ((Stud * 14.00) + (Wega * 16.50) + (Fish * 16.50) + (Luig * 16.50) + (Oris * 17.50 ) + (Master * 20.00) +(Vill * 18.50) + (Mari * 16.50) + (Schr * 16.50) + (Riem * 16.50 ) + (Tarz * 16.50))
    Cost =(SaucesCost + DrinksCost + PizzaCost)
    Tip = (Cost * 20)/100
    TipVal = F"{'%.2f zł'% Tip}"
    TipValue.set(TipVal)
    CostValue = F"{'%.2f zł'%Cost}"
    TotalValue.set(CostValue)
    TotalVal =str('%.2f zł'%((Cost + Tip)))
    FinalValue.set(TotalVal)  
#endregion
#region SAUCES
lblSauce = Label(LeftFrame, background='red', text="\tSAUCES\t\t")
lblSauce.grid(row =0, column=0)
Ketchup = Label(LeftFrame,background='lightgreen', text="\tKetchup\t\t2.00 zl").grid(row=1, column=0, sticky=W)
Ketchuptxt = Entry(LeftFrame, textvariable = KetchupValue, width =6 , justify ='left')
Ketchuptxt.grid(row = 1, column = 1)
Mayo = Label(LeftFrame,background='lightgreen', text="\tMayonnaise\t2.00 zł").grid(row=2, column=0, sticky=W)
Mayotxt = Entry(LeftFrame, textvariable = MayoValue, width =6 , justify ='left')
Mayotxt.grid(row = 2, column = 1)
Barbecue = Label(LeftFrame,background='lightgreen', text="\tBarbecue\t2.50 zł").grid(row=3, column=0, sticky=W)
Barbecuetxt = Entry(LeftFrame, textvariable = BarbecueValue, width =6 , justify ='left')
Barbecuetxt.grid(row = 3, column = 1)
Mustard = Label(LeftFrame, background='lightgreen', text="\tMustard\t\t2.50 zł").grid(row=4, column=0, sticky=W)
Mustardtxt = Entry(LeftFrame, textvariable = MustardValue, width =6 , justify ='left')
Mustardtxt.grid(row = 4, column = 1)
Salsa = Label(LeftFrame,background='lightgreen', text="\tSalsa\t\t3.00 zł").grid(row=5, column=0, sticky=W)
Salsatxt = Entry(LeftFrame,textvariable = SalsaValue, width =6 , justify ='left')
Salsatxt.grid(row = 5, column = 1)
Olive = Label(LeftFrame,background='lightgreen', text="\tOlive\t\t2.50 zł").grid(row=6, column=0, sticky=W)
OliveTxt = Entry(LeftFrame, textvariable = OliveValue, width =6 , justify ='left')
OliveTxt.grid(row = 6, column = 1)
Pumpkin = Label(LeftFrame,background='lightgreen', text="\tPumpkin\t3.50 zł").grid(row=7, column=0, sticky=W)
Pumpkintxt = Entry(LeftFrame, textvariable = PumpkinValue, width =6 , justify ='left')
Pumpkintxt.grid(row = 7, column = 1)
ArabicSpicy = Label(LeftFrame, background='lightgreen', text="\tArabic Spicy\t3.50 zł").grid(row=8, column=0, sticky=W)
ArabicSpicytxt = Entry(LeftFrame, textvariable = ArabicSpicyValue, width =6 , justify ='left')
ArabicSpicytxt.grid(row = 8, column = 1)
ArabicMild = Label(LeftFrame,background='lightgreen', text="\tArabic Mild\t2.50 zł").grid(row=9, column=0, sticky=W)
ArabicMildtxt  = Entry(LeftFrame, textvariable = ArabicMildValue, width =6 , justify ='left')
ArabicMildtxt.grid(row = 9, column = 1)
Danish = Label(LeftFrame,background='lightgreen', text="\tDanish\t\t3.50 zł").grid(row=10, column=0, sticky=W)
Danishtxt = Entry(LeftFrame, textvariable = DanishValue, width =6 , justify ='left')
Danishtxt.grid(row = 10, column = 1)
Horseradish = Label(LeftFrame,background='lightgreen', text="\tHorseradish\t2.50 zł").grid(row=11, column=0, sticky=W)
Horseradishtxt = Entry(LeftFrame,textvariable = HorseradishValue, width =6 , justify ='left')
Horseradishtxt.grid(row = 11, column = 1)
Hunter = Label(LeftFrame,background='lightgreen', text="\tHunter's\t\t2.50 zł").grid(row=12, column=0, sticky=W)
Huntertxt = Entry(LeftFrame, textvariable = HunterValue, width =6 , justify ='left')
Huntertxt.grid(row = 12, column = 1)
Cheese = Label(LeftFrame,background='lightgreen', text="\tCheese\t\t3.50 zł").grid(row=13, column=0, sticky=W)
Cheesetxt = Entry(LeftFrame, textvariable = CheeseValue, width =6 , justify ='left')
Cheesetxt.grid(row = 13, column = 1)
FrogsSecretSauce = Label(LeftFrame,background='lightgreen', text="        Frog's Secret Sauce      6.50 zł").grid(row=14, column=0, sticky=W)
FrogsSecretSaucetxt = Entry(LeftFrame, textvariable = FrogsSecretSauceValue, width =6 , justify ='left')
FrogsSecretSaucetxt.grid(row = 14, column = 1)
#endregion
#region DRINKS
lblDrink = Label(LeftFrame, background='red', text="\t DRINKS \t\t")
lblDrink.grid(row =15, column=0)
Water = Label(LeftFrame,background='lightgreen', text="\tClean Water\t0.50 zł").grid(row=16, column=0, sticky=W)
Watertxt = Entry(LeftFrame, textvariable = WaterValue, width =6 , justify ='left')
Watertxt.grid(row = 16, column = 1)
Pepsi = Label(LeftFrame,background='lightgreen', text="\tPepsi\t\t1.50 zł").grid(row=17, column=0, sticky=W)
Pepsitxt = Entry(LeftFrame, textvariable = PepsiValue, width =6 , justify ='left')
Pepsitxt.grid(row = 17, column = 1)
Tea = Label(LeftFrame,background='lightgreen', text="\tMint Tea\t\t1.50 zł").grid(row=18, column=0, sticky=W)
Teatxt = Entry(LeftFrame, textvariable = TeaValue, width =6 , justify ='left')
Teatxt.grid(row = 18, column = 1)
Coffee = Label(LeftFrame,background='lightgreen', text="\tCoffee\t\t1.50 zł").grid(row=19, column=0, sticky=W)
Coffeetxt = Entry(LeftFrame, textvariable = CoffeeValue, width =6 , justify ='left')
Coffeetxt.grid(row = 19, column = 1)
FrogsSecretMixture = Label(LeftFrame,background='lightgreen', text="       Frog's Secret Mixture      6.50 zł").grid(row=20, column=0, sticky=W)
FrogMixturetxt = Entry(LeftFrame, textvariable = FrogMixtureValue, width =6 , justify ='left')
FrogMixturetxt.grid(row = 20, column = 1)
#endregion
#region PIZZA
lblSide = Label(RightFrameTop, background='red', text="\t\t FROG'S PIZZA \t\t")
lblSide.grid(row =0, column=0)
Student = Label(RightFrameTop, background='lightgreen', text="\tStudent\t\t\t14.00 zł").grid(row=1, column=0, sticky=W)
Studenttxt = Entry(RightFrameTop, textvariable = StudentValue, width =6 , justify ='left')
Studenttxt.grid(row = 1, column = 1)
Wegan = Label(RightFrameTop, background='lightgreen', text="\tWegan (with one potato)\t16.50 zł").grid(row=2, column=0, sticky=W)
Wegantxt = Entry(RightFrameTop, textvariable = WeganValue, width =6 , justify ='left')
Wegantxt.grid(row = 2, column = 1)
Fisherman= Label(RightFrameTop, background='lightgreen', text="\tFisherman's Smile\t\t16.50 zł").grid(row=3, column=0, sticky=W)
Fishermantxt = Entry(RightFrameTop, textvariable = FishermanValue, width =6 , justify ='left')
Fishermantxt.grid(row = 3, column = 1)
Tarzan = Label(RightFrameTop, background='lightgreen', text="\tTarzan's Dinner\t\t16.50 zł").grid(row=4, column=0, sticky=W)
Tarzantxt = Entry(RightFrameTop, textvariable = TarzanValue, width =6 , justify ='left')
Tarzantxt.grid(row = 4, column = 1)
Riemann = Label(RightFrameTop, background='lightgreen',text="\tRiemann Integral\t\t16.50 zł").grid(row=5, column=0, sticky=W)
Riemanntxt = Entry(RightFrameTop, textvariable = RiemannValue, width =6 , justify ='left')
Riemanntxt.grid(row = 5, column = 1)
Schrödingera = Label(RightFrameTop, background='lightgreen', text="\tSchrödinger (we decide)\t16.50 zł").grid(row=6, column=0, sticky=W)
Schrödingeratxt = Entry(RightFrameTop, textvariable = SchrödingeraValue, width =6 , justify ='left')
Schrödingeratxt.grid(row = 6, column = 1)
Mario = Label(RightFrameTop,  background='lightgreen', text="\tMario's Pocket\t\t16.50 zł").grid(row=7, column=0, sticky=W)
Mariotxt = Entry(RightFrameTop, textvariable = MarioValue, width =6 , justify ='left')
Mariotxt.grid(row = 7, column = 1)
Luigi = Label(RightFrameTop, background='lightgreen', text="\tLuigi's BackUp Plan\t16.50 zł").grid(row=8, column=0, sticky=W)
Luigitxt = Entry(RightFrameTop, textvariable = LuigiValue, width =6 , justify ='left')
Luigitxt.grid(row = 8, column = 1)
Orissa = Label(RightFrameTop,  background='lightgreen',text="\tOrissa Tribute\t\t17.50 zł").grid(row=9, column=0, sticky=W)
Orissatxt = Entry(RightFrameTop, textvariable = OrissaValue, width =6 , justify ='left')
Orissatxt.grid(row = 9, column = 1)
Village  = Label(RightFrameTop,  background='lightgreen',text="\tLeaf Village Style\t\t18.50 zł").grid(row=10, column=0, sticky=W)
Villagetxt= Entry(RightFrameTop, textvariable = VillageValue, width =6 , justify ='left')
Villagetxt.grid(row = 10, column = 1)
Masterpiece  = Label(RightFrameTop,  background='lightgreen', text="\t    FROGGY MASTERPIECE   \t20.00zł").grid(row=11, column=0, sticky=W)
Masterpiecetxt = Entry(RightFrameTop, textvariable = MasterpieceValue, width =6 , justify ='left')
Masterpiecetxt.grid(row = 11, column = 1)
#endregion
#region Finish
Tipslbl = Label(RightFrameBottom, background='lightgreen',  text="     Tip    ", bd=10,  anchor = 'center')
Tipslbl.grid(row=1,column=0)
Tiptxt = Entry(RightFrameBottom, textvariable = TipValue, width =6, state = DISABLED)
Tiptxt.grid(row = 1, column = 2)
Totallbl = Label(RightFrameBottom, background='lightgreen', text="   Total   ", bd=10,  anchor = 'center')
Totallbl.grid(row=2,column=0)
Totaltxt = Entry(RightFrameBottom, textvariable = TotalValue, width =6, state = DISABLED)
Totaltxt.grid(row=2,column=2)
Finallbl = Label(RightFrameBottom, background='lightgreen', text="Final bill", bd=10,  anchor = 'center')
Finallbl.grid(row=3,column=0)
Totallbl = Entry(RightFrameBottom, textvariable = FinalValue, width =6, state = DISABLED)
Totallbl.grid(row=3,column=2)
btnTotal = Button(RightFrameBottom, padx=16, pady=1, bd=4, fg="black", bg="lightgreen", width = 5, text ="Total",command=FinalCountdown).grid(row=4, column = 0)
btnReset = Button(RightFrameBottom, padx=16, pady=1, bd=4, fg="Black", bg="lightgreen",width = 5, text ="Reset ",command=Reset).grid(row=4, column = 1)
btnExit = Button(RightFrameBottom, padx=16, pady=1, bd=4, fg="Black", bg="lightgreen",width = 5, text ="Exit", command=lambda: ExitButton(root)).grid(row=4, column = 2)
#endregion  
root.mainloop()
